import test from 'node:test';
import assert from 'node:assert/strict';
import { ApplicationError } from '@/common/errors/application.error';
import {
  buildAddColumn,
  buildAlterColumn,
  buildDropColumn,
  buildRenameTable,
  renderDefault,
} from '@/tables/alter-table.builder';

const TABLE = '"public"."widgets"';

test('a column is added with its type', () => {
  assert.equal(buildAddColumn(TABLE, { name: 'label', type: 'text' }), `ALTER TABLE ${TABLE} ADD COLUMN "label" text`);
});

test('a non-nullable column is marked NOT NULL', () => {
  assert.equal(
    buildAddColumn(TABLE, { name: 'label', type: 'text', nullable: false }),
    `ALTER TABLE ${TABLE} ADD COLUMN "label" text NOT NULL`,
  );
});

test('auto-generate maps to identity for integers and gen_random_uuid for uuid', () => {
  assert.match(buildAddColumn(TABLE, { name: 'n', type: 'bigint', autoGenerate: true }), /GENERATED BY DEFAULT AS IDENTITY$/);
  assert.match(buildAddColumn(TABLE, { name: 'u', type: 'uuid', autoGenerate: true }), /DEFAULT gen_random_uuid\(\)$/);
});

test('a type that cannot be auto-generated is refused', () => {
  assert.throws(() => buildAddColumn(TABLE, { name: 'x', type: 'text', autoGenerate: true }), /cannot be auto-generated/);
});

test('auto-generate and an explicit default are mutually exclusive', () => {
  assert.throws(
    () => buildAddColumn(TABLE, { name: 'u', type: 'uuid', autoGenerate: true, defaultValue: 'x' }),
    /cannot be auto-generated and have an explicit default/,
  );
});

test('an unsupported type never reaches SQL', () => {
  assert.throws(
    () => buildAddColumn(TABLE, { name: 'x', type: 'money; DROP TABLE t' as never }),
    (error: unknown) => error instanceof ApplicationError && error.code === 'bad_request',
  );
});

test('column names are quoted and internal quotes escaped', () => {
  assert.equal(
    buildAddColumn(TABLE, { name: 'we"ird', type: 'text' }),
    `ALTER TABLE ${TABLE} ADD COLUMN "we""ird" text`,
  );
});

// A quoted 'now()' would store the literal text once; the expression evaluates per row.
test('allowlisted defaults stay expressions, everything else is a quoted literal', () => {
  assert.equal(renderDefault('now()'), 'now()');
  assert.equal(renderDefault('NOW()'), 'now()');
  assert.equal(renderDefault('gen_random_uuid()'), 'gen_random_uuid()');
  assert.equal(renderDefault('true'), 'true');
  assert.equal(renderDefault('hello'), `'hello'`);
  assert.equal(renderDefault('42'), `'42'`);
});

test('a default containing a quote is escaped, not injected', () => {
  assert.equal(renderDefault(`'); DROP TABLE widgets; --`), `'''); DROP TABLE widgets; --'`);
});

test('a type change carries an explicit USING cast', () => {
  assert.deepEqual(buildAlterColumn(TABLE, 'qty', { type: 'integer' }), [
    `ALTER TABLE ${TABLE} ALTER COLUMN "qty" TYPE integer USING "qty"::integer`,
  ]);
});

test('nullability toggles both ways', () => {
  assert.deepEqual(buildAlterColumn(TABLE, 'label', { nullable: false }), [
    `ALTER TABLE ${TABLE} ALTER COLUMN "label" SET NOT NULL`,
  ]);
  assert.deepEqual(buildAlterColumn(TABLE, 'label', { nullable: true }), [
    `ALTER TABLE ${TABLE} ALTER COLUMN "label" DROP NOT NULL`,
  ]);
});

test('a default can be set or dropped', () => {
  assert.deepEqual(buildAlterColumn(TABLE, 'label', { defaultValue: 'none' }), [
    `ALTER TABLE ${TABLE} ALTER COLUMN "label" SET DEFAULT 'none'`,
  ]);
  assert.deepEqual(buildAlterColumn(TABLE, 'label', { dropDefault: true }), [
    `ALTER TABLE ${TABLE} ALTER COLUMN "label" DROP DEFAULT`,
  ]);
});

test('setting and dropping a default at once is refused as ambiguous', () => {
  assert.throws(
    () => buildAlterColumn(TABLE, 'label', { defaultValue: 'x', dropDefault: true }),
    /Cannot set and drop a default/,
  );
});

test('independent changes combine into a single ALTER TABLE', () => {
  assert.deepEqual(buildAlterColumn(TABLE, 'qty', { type: 'integer', nullable: false, defaultValue: '0' }), [
    `ALTER TABLE ${TABLE} ALTER COLUMN "qty" TYPE integer USING "qty"::integer,`
      + ` ALTER COLUMN "qty" SET NOT NULL, ALTER COLUMN "qty" SET DEFAULT '0'`,
  ]);
});

// PostgreSQL will not accept RENAME COLUMN alongside other actions, so it is a second
// statement — and it comes last so the first can still name the column as it is today.
test('a rename is a separate statement, applied after the other changes', () => {
  const statements = buildAlterColumn(TABLE, 'qty', { name: 'quantity', type: 'integer' });
  assert.equal(statements.length, 2);
  assert.match(statements[0]!, /ALTER COLUMN "qty" TYPE integer/);
  assert.equal(statements[1], `ALTER TABLE ${TABLE} RENAME COLUMN "qty" TO "quantity"`);
});

test('a rename alone produces just the rename', () => {
  assert.deepEqual(buildAlterColumn(TABLE, 'qty', { name: 'quantity' }), [
    `ALTER TABLE ${TABLE} RENAME COLUMN "qty" TO "quantity"`,
  ]);
});

test('renaming a column to its current name is not a change', () => {
  assert.throws(() => buildAlterColumn(TABLE, 'qty', { name: 'qty' }), /No column changes were requested/);
});

test('an empty change set is refused rather than issuing empty SQL', () => {
  assert.throws(() => buildAlterColumn(TABLE, 'qty', {}), /No column changes were requested/);
});

test('drop column does not cascade', () => {
  const sql = buildDropColumn(TABLE, 'qty');
  assert.equal(sql, `ALTER TABLE ${TABLE} DROP COLUMN "qty"`);
  assert.doesNotMatch(sql, /CASCADE/);
});

test('rename table takes a bare, quoted target name', () => {
  assert.equal(buildRenameTable(TABLE, 'gadgets'), `ALTER TABLE ${TABLE} RENAME TO "gadgets"`);
});

test('an injection attempt in a rename is quoted, not executed', () => {
  assert.equal(
    buildRenameTable(TABLE, 'x"; DROP TABLE widgets; --'),
    `ALTER TABLE ${TABLE} RENAME TO "x""; DROP TABLE widgets; --"`,
  );
});
