import { ApplicationError } from '@/common/errors/application.error';
import { ALLOWED_COLUMN_TYPES, ColumnType } from '@/common/allowed-types';
import { quoteIdentifier, quoteLiteral } from '@/db/sql.util';

const INTEGER_TYPES: readonly string[] = ['integer', 'bigint', 'smallint'];

/**
 * Expressions accepted verbatim as a column DEFAULT.
 *
 * PostgreSQL cannot parameterize a DEFAULT, so anything else is emitted as a quoted
 * string literal and left for PostgreSQL to coerce to the column type. These few are
 * allowlisted because quoting them would freeze them: `DEFAULT 'now()'` stores the
 * literal text, and `DEFAULT now()` evaluates per row, which is what people mean.
 */
const DEFAULT_EXPRESSIONS = new Map<string, string>([
  ['now()', 'now()'],
  ['current_timestamp', 'CURRENT_TIMESTAMP'],
  ['current_date', 'CURRENT_DATE'],
  ['current_time', 'CURRENT_TIME'],
  ['gen_random_uuid()', 'gen_random_uuid()'],
  ['true', 'true'],
  ['false', 'false'],
  ['null', 'NULL'],
]);

export interface AddColumnRequest {
  name: string;
  type: ColumnType;
  nullable?: boolean | undefined;
  autoGenerate?: boolean | undefined;
  defaultValue?: string | undefined;
}

export interface AlterColumnRequest {
  /** New name for the column; omitted leaves it alone. */
  name?: string | undefined;
  type?: ColumnType | undefined;
  nullable?: boolean | undefined;
  defaultValue?: string | undefined;
  dropDefault?: boolean | undefined;
}

function assertKnownType(type: string): asserts type is ColumnType {
  if (!ALLOWED_COLUMN_TYPES.includes(type as ColumnType)) {
    throw ApplicationError.badRequest(`Unsupported type: ${type}`);
  }
}

/** Renders a DEFAULT clause value: an allowlisted expression, or a quoted literal. */
export function renderDefault(value: string): string {
  return DEFAULT_EXPRESSIONS.get(value.trim().toLowerCase()) ?? quoteLiteral(value);
}

export function buildAddColumn(qualified: string, request: AddColumnRequest): string {
  assertKnownType(request.type);
  if (request.autoGenerate && request.defaultValue !== undefined) {
    throw ApplicationError.badRequest('A column cannot be auto-generated and have an explicit default');
  }

  let definition = `${quoteIdentifier(request.name)} ${request.type}`;
  if (request.autoGenerate && INTEGER_TYPES.includes(request.type)) {
    definition += ' GENERATED BY DEFAULT AS IDENTITY';
  } else if (request.autoGenerate && request.type === 'uuid') {
    definition += ' DEFAULT gen_random_uuid()';
  } else if (request.autoGenerate) {
    throw ApplicationError.badRequest(`Type ${request.type} cannot be auto-generated`);
  }
  if (request.defaultValue !== undefined) definition += ` DEFAULT ${renderDefault(request.defaultValue)}`;
  if (request.nullable === false) definition += ' NOT NULL';

  return `ALTER TABLE ${qualified} ADD COLUMN ${definition}`;
}

/**
 * Compiles a column change into the statements that apply it, in order.
 *
 * Type, nullability and default combine into one `ALTER TABLE`, so PostgreSQL validates
 * them together. A rename cannot be combined with those, so it is a second statement —
 * which is why the caller runs the result in a transaction. It is emitted last so the
 * earlier statement can still refer to the column by its current name.
 */
export function buildAlterColumn(qualified: string, column: string, request: AlterColumnRequest): string[] {
  if (request.defaultValue !== undefined && request.dropDefault) {
    throw ApplicationError.badRequest('Cannot set and drop a default in the same change');
  }

  const current = quoteIdentifier(column);
  const actions: string[] = [];

  if (request.type !== undefined) {
    assertKnownType(request.type);
    // Without USING, PostgreSQL refuses any conversion that is not binary-coercible
    // (text -> integer, for example); the explicit cast makes the common cases work.
    actions.push(`ALTER COLUMN ${current} TYPE ${request.type} USING ${current}::${request.type}`);
  }
  if (request.nullable !== undefined) {
    actions.push(`ALTER COLUMN ${current} ${request.nullable ? 'DROP NOT NULL' : 'SET NOT NULL'}`);
  }
  if (request.defaultValue !== undefined) {
    actions.push(`ALTER COLUMN ${current} SET DEFAULT ${renderDefault(request.defaultValue)}`);
  }
  if (request.dropDefault) {
    actions.push(`ALTER COLUMN ${current} DROP DEFAULT`);
  }

  const statements: string[] = [];
  if (actions.length > 0) statements.push(`ALTER TABLE ${qualified} ${actions.join(', ')}`);
  if (request.name !== undefined && request.name !== column) {
    statements.push(`ALTER TABLE ${qualified} RENAME COLUMN ${current} TO ${quoteIdentifier(request.name)}`);
  }

  if (statements.length === 0) throw ApplicationError.badRequest('No column changes were requested');
  return statements;
}

export function buildDropColumn(qualified: string, column: string): string {
  // No CASCADE: PostgreSQL's own error naming the dependent view or constraint is more
  // useful than silently dropping it, matching how table and schema drops behave.
  return `ALTER TABLE ${qualified} DROP COLUMN ${quoteIdentifier(column)}`;
}

export function buildRenameTable(qualified: string, newName: string): string {
  // RENAME TO takes a bare name — the table cannot change schema this way.
  return `ALTER TABLE ${qualified} RENAME TO ${quoteIdentifier(newName)}`;
}
