import { Inject, Injectable } from '@nestjs/common';
import { ApplicationError } from '@/common/errors/application.error';
import { ALLOWED_COLUMN_TYPES } from '@/common/allowed-types';
import { PROJECT_DATABASE, ProjectDatabase } from '@/db/tenant/database.ports';
import { normalizeSchema, qualifiedName } from '@/db/sql.util';
import { CreateTableDto } from '@/tables/dto/create-table.dto';
import { buildRowQuery, DEFAULT_ROW_LIMIT } from '@/tables/row-query.builder';
import {
  AddColumnRequest,
  AlterColumnRequest,
  buildAddColumn,
  buildAlterColumn,
  buildDropColumn,
  buildRenameTable,
} from '@/tables/alter-table.builder';
import { TableMetadataService } from '@/tables/table-metadata.service';
import { ColumnInfo, encodeRowCursor, RowsResponse, TableInfo } from '@/tables/tables.types';
import { ListRowsOptions, TablesApplication } from '@/tables/tables-service.port';

const INTEGER_TYPES = ['integer', 'bigint', 'smallint'];

@Injectable()
export class TablesService implements TablesApplication {
  constructor(
    @Inject(PROJECT_DATABASE) private readonly db: ProjectDatabase,
    private readonly metadata: TableMetadataService,
  ) {}

  /** Loads the table's columns, or fails if it does not exist. */
  private async requireColumns(table: string, schema: string): Promise<ColumnInfo[]> {
    const columns = await this.metadata.columns(table, schema);
    if (columns.length === 0) throw ApplicationError.notFound('Table not found');
    return columns;
  }

  private async requireTable(table: string, schema: string): Promise<void> {
    if (!(await this.metadata.exists(table, schema))) throw ApplicationError.notFound('Table not found');
  }

  async listTables(schema?: string): Promise<TableInfo[]> {
    const { rows } = await this.db.query<TableInfo>(
      `SELECT relname AS name
       FROM pg_class
       JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
       WHERE pg_namespace.nspname = $1 AND pg_class.relkind = 'r'
       ORDER BY relname`,
      [normalizeSchema(schema)],
    );
    return rows;
  }

  async createTable(dto: CreateTableDto, schema?: string): Promise<void> {
    const schemaName = normalizeSchema(schema);
    const colDefs = dto.columns.map((col) => {
      if (!ALLOWED_COLUMN_TYPES.includes(col.type)) {
        throw ApplicationError.badRequest(`Unsupported type: ${col.type}`);
      }
      let def = `${this.db.quoteIdent(col.name)} ${col.type}`;
      if (col.autoGenerate && INTEGER_TYPES.includes(col.type)) {
        def += ' GENERATED BY DEFAULT AS IDENTITY';
      } else if (col.autoGenerate && col.type === 'uuid') {
        def += ' DEFAULT gen_random_uuid()';
      }
      if (col.primaryKey) def += ' PRIMARY KEY';
      if (col.nullable === false && !col.primaryKey) def += ' NOT NULL';
      return def;
    });

    try {
      await this.db.query(`CREATE TABLE ${qualifiedName(schemaName, dto.name)} (${colDefs.join(', ')})`);
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }

  async dropTable(table: string, schema?: string): Promise<void> {
    const schemaName = normalizeSchema(schema);
    await this.requireTable(table, schemaName);
    try {
      await this.db.query(`DROP TABLE ${qualifiedName(schemaName, table)}`);
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }

  /** Fails unless the column exists on the table, so a typo is not reported as a driver error. */
  private async requireColumn(table: string, column: string, schema: string): Promise<void> {
    const columns = await this.requireColumns(table, schema);
    if (!columns.some((c) => c.column_name === column)) {
      throw ApplicationError.notFound(`Column not found: ${column}`);
    }
  }

  async addColumn(table: string, request: AddColumnRequest, schema?: string): Promise<void> {
    const schemaName = normalizeSchema(schema);
    await this.requireTable(table, schemaName);
    try {
      await this.db.query(buildAddColumn(qualifiedName(schemaName, table), request));
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }

  async alterColumn(table: string, column: string, request: AlterColumnRequest, schema?: string): Promise<void> {
    const schemaName = normalizeSchema(schema);
    await this.requireColumn(table, column, schemaName);
    const statements = buildAlterColumn(qualifiedName(schemaName, table), column, request);
    try {
      // A rename is a separate statement from a type/nullability change; without the
      // transaction a failure halfway would leave the column renamed but not retyped.
      await this.db.transaction(async (tx) => {
        for (const statement of statements) await tx.query(statement);
      });
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }

  async dropColumn(table: string, column: string, schema?: string): Promise<void> {
    const schemaName = normalizeSchema(schema);
    await this.requireColumn(table, column, schemaName);
    try {
      await this.db.query(buildDropColumn(qualifiedName(schemaName, table), column));
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }

  async renameTable(table: string, newName: string, schema?: string): Promise<void> {
    const schemaName = normalizeSchema(schema);
    await this.requireTable(table, schemaName);
    try {
      await this.db.query(buildRenameTable(qualifiedName(schemaName, table), newName));
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }

  async getSchema(table: string, schema?: string): Promise<ColumnInfo[]> {
    const schemaName = normalizeSchema(schema);
    await this.requireTable(table, schemaName);
    return this.metadata.columns(table, schemaName);
  }

  async getRows(options: ListRowsOptions): Promise<RowsResponse> {
    const { table, filters, cursor, sort, includeTotal = true } = options;
    const schemaName = normalizeSchema(options.schema);
    const columns = await this.requireColumns(table, schemaName);
    const query = buildRowQuery(
      {
        columns,
        limit: options.limit ?? DEFAULT_ROW_LIMIT,
        offset: options.offset ?? 0,
        filters,
        cursor,
        sort,
      },
      (name) => this.db.quoteIdent(name),
    );
    const qualified = qualifiedName(schemaName, table);

    try {
      const { rows } = await this.db.query(
        `SELECT * FROM ${qualified} ${query.whereSql} ${query.orderSql}
         LIMIT $${query.whereParams.length + 1} OFFSET $${query.whereParams.length + 2}`,
        [...query.whereParams, query.limit, query.offset],
      );

      let total: number | null = null;
      if (includeTotal) {
        const { rows: countRows } = await this.db.query<{ count: string }>(
          `SELECT COUNT(*)::bigint AS count FROM ${qualified} ${query.countWhereSql}`,
          query.countParams,
        );
        total = Number(countRows[0]?.count ?? 0);
      }

      const last = rows.at(-1);
      const nextCursor = query.cursorColumn && last && rows.length === query.limit
        ? encodeRowCursor(query.cursorColumn, last[query.cursorColumn])
        : undefined;
      return { rows, total, nextCursor };
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }

  async insertRow(table: string, values: Record<string, unknown>, schema?: string): Promise<Record<string, unknown>> {
    const schemaName = normalizeSchema(schema);
    const columns = await this.requireColumns(table, schemaName);
    const validNames = new Set(columns.map((c) => c.column_name));
    const keys = Object.keys(values ?? {}).filter((key) => validNames.has(key));
    const qualified = qualifiedName(schemaName, table);

    try {
      if (keys.length === 0) {
        const { rows } = await this.db.query(`INSERT INTO ${qualified} DEFAULT VALUES RETURNING *`);
        return requireRow(rows);
      }
      const colSql = keys.map((key) => this.db.quoteIdent(key)).join(', ');
      const paramSql = keys.map((_, index) => `$${index + 1}`).join(', ');
      const { rows } = await this.db.query(
        `INSERT INTO ${qualified} (${colSql}) VALUES (${paramSql}) RETURNING *`,
        keys.map((key) => values[key]),
      );
      return requireRow(rows);
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }

  async updateRow(
    table: string,
    pk: Record<string, unknown>,
    values: Record<string, unknown>,
    schema?: string,
  ): Promise<Record<string, unknown>> {
    const schemaName = normalizeSchema(schema);
    const columns = await this.requireColumns(table, schemaName);
    const validNames = new Set(columns.map((c) => c.column_name));

    const setKeys = Object.keys(values ?? {}).filter((key) => validNames.has(key));
    if (setKeys.length === 0) throw ApplicationError.badRequest('No valid columns to update');
    const pkKeys = requirePkKeys(pk, validNames);

    const setSql = setKeys.map((key, index) => `${this.db.quoteIdent(key)} = $${index + 1}`).join(', ');
    const whereSql = pkKeys
      .map((key, index) => `${this.db.quoteIdent(key)} = $${setKeys.length + index + 1}`)
      .join(' AND ');
    const params = [...setKeys.map((key) => values[key]), ...pkKeys.map((key) => pk[key])];

    try {
      const { rows } = await this.db.query(
        `UPDATE ${qualifiedName(schemaName, table)} SET ${setSql} WHERE ${whereSql} RETURNING *`,
        params,
      );
      const row = rows[0];
      if (!row) throw ApplicationError.notFound('Row not found');
      return row;
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }

  async deleteRow(table: string, pk: Record<string, unknown>, schema?: string): Promise<void> {
    const schemaName = normalizeSchema(schema);
    const columns = await this.requireColumns(table, schemaName);
    const pkKeys = requirePkKeys(pk, new Set(columns.map((c) => c.column_name)));
    const whereSql = pkKeys.map((key, index) => `${this.db.quoteIdent(key)} = $${index + 1}`).join(' AND ');

    try {
      const { rowCount } = await this.db.query(
        `DELETE FROM ${qualifiedName(schemaName, table)} WHERE ${whereSql}`,
        pkKeys.map((key) => pk[key]),
      );
      if (rowCount === 0) throw ApplicationError.notFound('Row not found');
    } catch (err) {
      throw ApplicationError.fromDriver(err);
    }
  }
}

function requireRow(rows: Record<string, unknown>[]): Record<string, unknown> {
  const row = rows[0];
  if (!row) throw ApplicationError.badRequest('Statement returned no row');
  return row;
}

function requirePkKeys(pk: Record<string, unknown>, validNames: Set<string>): string[] {
  if (!pk || Object.keys(pk).length === 0) throw ApplicationError.badRequest('pk is required');
  const pkKeys = Object.keys(pk).filter((key) => validNames.has(key));
  if (pkKeys.length === 0) throw ApplicationError.badRequest('Invalid pk columns');
  return pkKeys;
}
